#ifndef YT_ROUTE_H
#define YT_ROUTE_H

#define YT_ROUTE_CAPACITY 3001U
#define YT_ROUTE_AVOID_COUNT 30U

enum yt_route_outcome {
	YT_ROUTE_SAME,
	YT_ROUTE_FOUND,
	YT_ROUTE_NOT_FOUND,
	YT_ROUTE_BACK_EDGE,
};

#endif
